/**
 * Exercise image utility for TrackYourLift.
 *
 * Images come from the yuhonas/free-exercise-db repository on GitHub.
 * URL format: https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{ID}/0.jpg
 *
 * Keys in EXERCISE_IMAGE_IDS cover every name seeded in server/db.ts plus
 * common alternate spellings so existing workout history continues to work.
 */

const BASE_URL =
  "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

/**
 * Maps exercise display names → free-exercise-db folder IDs.
 * Both plural and singular forms are included to handle workout history
 * saved under either convention.
 *
 * When the free-exercise-db has no exact match, the closest movement
 * pattern is used so users always see a relevant image rather than the
 * generic muscle-group placeholder.
 */
const EXERCISE_IMAGE_IDS: Record<string, string> = {
  // --- free-exercise-db catalog expansion (2026-07) ---
  "3/4 Sit-Up": "3_4_Sit-Up",
  "90/90 Hamstring": "90_90_Hamstring",
  "Ab Crunch Machine": "Ab_Crunch_Machine",
  "Ab Roller": "Ab_Roller",
  "Adductor": "Adductor",
  "Adductor/Groin": "Adductor_Groin",
  "Advanced Kettlebell Windmill": "Advanced_Kettlebell_Windmill",
  "Air Bike": "Air_Bike",
  "All Fours Quad Stretch": "All_Fours_Quad_Stretch",
  "Alternate Hammer Curl": "Alternate_Hammer_Curl",
  "Alternate Heel Touchers": "Alternate_Heel_Touchers",
  "Alternate Incline Dumbbell Curl": "Alternate_Incline_Dumbbell_Curl",
  "Alternate Leg Diagonal Bound": "Alternate_Leg_Diagonal_Bound",
  "Alternating Cable Shoulder Press": "Alternating_Cable_Shoulder_Press",
  "Alternating Deltoid Raise": "Alternating_Deltoid_Raise",
  "Alternating Floor Press": "Alternating_Floor_Press",
  "Alternating Hang Clean": "Alternating_Hang_Clean",
  "Alternating Kettlebell Press": "Alternating_Kettlebell_Press",
  "Alternating Kettlebell Row": "Alternating_Kettlebell_Row",
  "Alternating Renegade Row": "Alternating_Renegade_Row",
  "Ankle Circles": "Ankle_Circles",
  "Ankle On The Knee": "Ankle_On_The_Knee",
  "Anterior Tibialis-SMR": "Anterior_Tibialis-SMR",
  "Anti-Gravity Press": "Anti-Gravity_Press",
  "Arm Circles": "Arm_Circles",
  "Around The Worlds": "Around_The_Worlds",
  "Atlas Stone Trainer": "Atlas_Stone_Trainer",
  "Atlas Stones": "Atlas_Stones",
  "Axle Deadlift": "Axle_Deadlift",
  "Back Flyes - With Bands": "Back_Flyes_-_With_Bands",
  "Backward Drag": "Backward_Drag",
  "Backward Medicine Ball Throw": "Backward_Medicine_Ball_Throw",
  "Balance Board": "Balance_Board",
  "Ball Leg Curl": "Ball_Leg_Curl",
  "Band Assisted Pull-Up": "Band_Assisted_Pull-Up",
  "Band Good Morning": "Band_Good_Morning",
  "Band Good Morning (Pull Through)": "Band_Good_Morning_Pull_Through",
  "Band Hip Adductions": "Band_Hip_Adductions",
  "Band Pull Apart": "Band_Pull_Apart",
  "Band Skull Crusher": "Band_Skull_Crusher",
  "Barbell Ab Rollout": "Barbell_Ab_Rollout",
  "Barbell Ab Rollout - On Knees": "Barbell_Ab_Rollout_-_On_Knees",
  "Barbell Bench Press - Medium Grip": "Barbell_Bench_Press_-_Medium_Grip",
  "Barbell Curls Lying Against An Incline": "Barbell_Curls_Lying_Against_An_Incline",
  "Barbell Full Squat": "Barbell_Full_Squat",
  "Barbell Glute Bridge": "Barbell_Glute_Bridge",
  "Barbell Guillotine Bench Press": "Barbell_Guillotine_Bench_Press",
  "Barbell Hack Squat": "Barbell_Hack_Squat",
  "Barbell Incline Bench Press - Medium Grip": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "Barbell Incline Shoulder Raise": "Barbell_Incline_Shoulder_Raise",
  "Barbell Lunge": "Barbell_Lunge",
  "Barbell Rear Delt Row": "Barbell_Rear_Delt_Row",
  "Barbell Rollout from Bench": "Barbell_Rollout_from_Bench",
  "Barbell Seated Calf Raise": "Barbell_Seated_Calf_Raise",
  "Barbell Shoulder Press": "Barbell_Shoulder_Press",
  "Barbell Shrug Behind The Back": "Barbell_Shrug_Behind_The_Back",
  "Barbell Side Bend": "Barbell_Side_Bend",
  "Barbell Side Split Squat": "Barbell_Side_Split_Squat",
  "Barbell Squat To A Bench": "Barbell_Squat_To_A_Bench",
  "Barbell Step Ups": "Barbell_Step_Ups",
  "Barbell Walking Lunge": "Barbell_Walking_Lunge",
  "Battling Ropes": "Battling_Ropes",
  "Bear Crawl Sled Drags": "Bear_Crawl_Sled_Drags",
  "Behind Head Chest Stretch": "Behind_Head_Chest_Stretch",
  "Bench Dips": "Bench_Dips",
  "Bench Jump": "Bench_Jump",
  "Bench Press - Powerlifting": "Bench_Press_-_Powerlifting",
  "Bench Press - With Bands": "Bench_Press_-_With_Bands",
  "Bench Press with Chains": "Bench_Press_with_Chains",
  "Bench Sprint": "Bench_Sprint",
  "Bent-Arm Barbell Pullover": "Bent-Arm_Barbell_Pullover",
  "Bent-Arm Dumbbell Pullover": "Bent-Arm_Dumbbell_Pullover",
  "Bent-Knee Hip Raise": "Bent-Knee_Hip_Raise",
  "Bent Over Barbell Row": "Bent_Over_Barbell_Row",
  "Bent Over Dumbbell Rear Delt Raise With Head On Bench": "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
  "Bent Over Low-Pulley Side Lateral": "Bent_Over_Low-Pulley_Side_Lateral",
  "Bent Over One-Arm Long Bar Row": "Bent_Over_One-Arm_Long_Bar_Row",
  "Bent Over Two-Arm Long Bar Row": "Bent_Over_Two-Arm_Long_Bar_Row",
  "Bent Over Two-Dumbbell Row": "Bent_Over_Two-Dumbbell_Row",
  "Bent Over Two-Dumbbell Row With Palms In": "Bent_Over_Two-Dumbbell_Row_With_Palms_In",
  "Bent Press": "Bent_Press",
  "Bicycling": "Bicycling",
  "Bicycling, Stationary": "Bicycling_Stationary",
  "Board Press": "Board_Press",
  "Body-Up": "Body-Up",
  "Body Tricep Press": "Body_Tricep_Press",
  "Bodyweight Flyes": "Bodyweight_Flyes",
  "Bodyweight Mid Row": "Bodyweight_Mid_Row",
  "Bodyweight Walking Lunge": "Bodyweight_Walking_Lunge",
  "Bosu Ball Cable Crunch With Side Bends": "Bosu_Ball_Cable_Crunch_With_Side_Bends",
  "Bottoms-Up Clean From The Hang Position": "Bottoms-Up_Clean_From_The_Hang_Position",
  "Bottoms Up": "Bottoms_Up",
  "Box Jump (Multiple Response)": "Box_Jump_Multiple_Response",
  "Box Skip": "Box_Skip",
  "Box Squat": "Box_Squat",
  "Box Squat with Bands": "Box_Squat_with_Bands",
  "Box Squat with Chains": "Box_Squat_with_Chains",
  "Brachialis-SMR": "Brachialis-SMR",
  "Bradford/Rocky Presses": "Bradford_Rocky_Presses",
  "Butt-Ups": "Butt-Ups",
  "Butt Lift (Bridge)": "Butt_Lift_Bridge",
  "Butterfly": "Butterfly",
  "Cable Chest Press": "Cable_Chest_Press",
  "Cable Crossover": "Cable_Crossover",
  "Cable Deadlifts": "Cable_Deadlifts",
  "Cable Hammer Curls - Rope Attachment": "Cable_Hammer_Curls_-_Rope_Attachment",
  "Cable Hip Adduction": "Cable_Hip_Adduction",
  "Cable Incline Pushdown": "Cable_Incline_Pushdown",
  "Cable Incline Triceps Extension": "Cable_Incline_Triceps_Extension",
  "Cable Internal Rotation": "Cable_Internal_Rotation",
  "Cable Iron Cross": "Cable_Iron_Cross",
  "Cable Judo Flip": "Cable_Judo_Flip",
  "Cable Lying Triceps Extension": "Cable_Lying_Triceps_Extension",
  "Cable One Arm Tricep Extension": "Cable_One_Arm_Tricep_Extension",
  "Cable Preacher Curl": "Cable_Preacher_Curl",
  "Cable Rear Delt Fly": "Cable_Rear_Delt_Fly",
  "Cable Reverse Crunch": "Cable_Reverse_Crunch",
  "Cable Rope Overhead Triceps Extension": "Cable_Rope_Overhead_Triceps_Extension",
  "Cable Rope Rear-Delt Rows": "Cable_Rope_Rear-Delt_Rows",
  "Cable Russian Twists": "Cable_Russian_Twists",
  "Cable Seated Crunch": "Cable_Seated_Crunch",
  "Cable Seated Lateral Raise": "Cable_Seated_Lateral_Raise",
  "Cable Shoulder Press": "Cable_Shoulder_Press",
  "Cable Shrugs": "Cable_Shrugs",
  "Cable Wrist Curl": "Cable_Wrist_Curl",
  "Calf-Machine Shoulder Shrug": "Calf-Machine_Shoulder_Shrug",
  "Calf Press": "Calf_Press",
  "Calf Press On The Leg Press Machine": "Calf_Press_On_The_Leg_Press_Machine",
  "Calf Raise On A Dumbbell": "Calf_Raise_On_A_Dumbbell",
  "Calf Raises - With Bands": "Calf_Raises_-_With_Bands",
  "Calf Stretch Elbows Against Wall": "Calf_Stretch_Elbows_Against_Wall",
  "Calf Stretch Hands Against Wall": "Calf_Stretch_Hands_Against_Wall",
  "Calves-SMR": "Calves-SMR",
  "Car Deadlift": "Car_Deadlift",
  "Car Drivers": "Car_Drivers",
  "Carioca Quick Step": "Carioca_Quick_Step",
  "Cat Stretch": "Cat_Stretch",
  "Catch and Overhead Throw": "Catch_and_Overhead_Throw",
  "Chain Handle Extension": "Chain_Handle_Extension",
  "Chain Press": "Chain_Press",
  "Chair Leg Extended Stretch": "Chair_Leg_Extended_Stretch",
  "Chair Lower Back Stretch": "Chair_Lower_Back_Stretch",
  "Chair Squat": "Chair_Squat",
  "Chair Upper Body Stretch": "Chair_Upper_Body_Stretch",
  "Chest And Front Of Shoulder Stretch": "Chest_And_Front_Of_Shoulder_Stretch",
  "Chest Push from 3 point stance": "Chest_Push_from_3_point_stance",
  "Chest Push (multiple response)": "Chest_Push_multiple_response",
  "Chest Push (single response)": "Chest_Push_single_response",
  "Chest Push with Run Release": "Chest_Push_with_Run_Release",
  "Chest Stretch on Stability Ball": "Chest_Stretch_on_Stability_Ball",
  "Child's Pose": "Childs_Pose",
  "Chin-Up": "Chin-Up",
  "Chin To Chest Stretch": "Chin_To_Chest_Stretch",
  "Circus Bell": "Circus_Bell",
  "Clean": "Clean",
  "Clean Deadlift": "Clean_Deadlift",
  "Clean Pull": "Clean_Pull",
  "Clean Shrug": "Clean_Shrug",
  "Clean and Jerk": "Clean_and_Jerk",
  "Clean from Blocks": "Clean_from_Blocks",
  "Clock Push-Up": "Clock_Push-Up",
  "Close-Grip Barbell Bench Press": "Close-Grip_Barbell_Bench_Press",
  "Close-Grip Dumbbell Press": "Close-Grip_Dumbbell_Press",
  "Close-Grip EZ-Bar Curl with Band": "Close-Grip_EZ-Bar_Curl_with_Band",
  "Close-Grip EZ-Bar Press": "Close-Grip_EZ-Bar_Press",
  "Close-Grip EZ Bar Curl": "Close-Grip_EZ_Bar_Curl",
  "Close-Grip Front Lat Pulldown": "Close-Grip_Front_Lat_Pulldown",
  "Close-Grip Push-Up off of a Dumbbell": "Close-Grip_Push-Up_off_of_a_Dumbbell",
  "Close-Grip Standing Barbell Curl": "Close-Grip_Standing_Barbell_Curl",
  "Cocoons": "Cocoons",
  "Conan's Wheel": "Conans_Wheel",
  "Concentration Curls": "Concentration_Curls",
  "Cross-Body Crunch": "Cross-Body_Crunch",
  "Cross Body Hammer Curl": "Cross_Body_Hammer_Curl",
  "Cross Over - With Bands": "Cross_Over_-_With_Bands",
  "Crossover Reverse Lunge": "Crossover_Reverse_Lunge",
  "Crucifix": "Crucifix",
  "Crunch - Hands Overhead": "Crunch_-_Hands_Overhead",
  "Crunch - Legs On Exercise Ball": "Crunch_-_Legs_On_Exercise_Ball",
  "Cuban Press": "Cuban_Press",
  "Dancer's Stretch": "Dancers_Stretch",
  "Deadlift with Bands": "Deadlift_with_Bands",
  "Deadlift with Chains": "Deadlift_with_Chains",
  "Decline Close-Grip Bench To Skull Crusher": "Decline_Close-Grip_Bench_To_Skull_Crusher",
  "Decline Crunch": "Decline_Crunch",
  "Decline Dumbbell Bench Press": "Decline_Dumbbell_Bench_Press",
  "Decline Dumbbell Flyes": "Decline_Dumbbell_Flyes",
  "Decline Dumbbell Triceps Extension": "Decline_Dumbbell_Triceps_Extension",
  "Decline EZ Bar Triceps Extension": "Decline_EZ_Bar_Triceps_Extension",
  "Decline Oblique Crunch": "Decline_Oblique_Crunch",
  "Decline Push-Up": "Decline_Push-Up",
  "Decline Reverse Crunch": "Decline_Reverse_Crunch",
  "Decline Smith Press": "Decline_Smith_Press",
  "Depth Jump Leap": "Depth_Jump_Leap",
  "Dip Machine": "Dip_Machine",
  "Dips - Chest Version": "Dips_-_Chest_Version",
  "Dips - Triceps Version": "Dips_-_Triceps_Version",
  "Donkey Calf Raises": "Donkey_Calf_Raises",
  "Double Kettlebell Alternating Hang Clean": "Double_Kettlebell_Alternating_Hang_Clean",
  "Double Kettlebell Jerk": "Double_Kettlebell_Jerk",
  "Double Kettlebell Push Press": "Double_Kettlebell_Push_Press",
  "Double Kettlebell Snatch": "Double_Kettlebell_Snatch",
  "Double Kettlebell Windmill": "Double_Kettlebell_Windmill",
  "Double Leg Butt Kick": "Double_Leg_Butt_Kick",
  "Downward Facing Balance": "Downward_Facing_Balance",
  "Drag Curl": "Drag_Curl",
  "Drop Push": "Drop_Push",
  "Dumbbell Alternate Bicep Curl": "Dumbbell_Alternate_Bicep_Curl",
  "Dumbbell Bench Press with Neutral Grip": "Dumbbell_Bench_Press_with_Neutral_Grip",
  "Dumbbell Clean": "Dumbbell_Clean",
  "Dumbbell Incline Row": "Dumbbell_Incline_Row",
  "Dumbbell Incline Shoulder Raise": "Dumbbell_Incline_Shoulder_Raise",
  "Dumbbell Lying One-Arm Rear Lateral Raise": "Dumbbell_Lying_One-Arm_Rear_Lateral_Raise",
  "Dumbbell Lying Pronation": "Dumbbell_Lying_Pronation",
  "Dumbbell Lying Rear Lateral Raise": "Dumbbell_Lying_Rear_Lateral_Raise",
  "Dumbbell Lying Supination": "Dumbbell_Lying_Supination",
  "Dumbbell One-Arm Shoulder Press": "Dumbbell_One-Arm_Shoulder_Press",
  "Dumbbell One-Arm Triceps Extension": "Dumbbell_One-Arm_Triceps_Extension",
  "Dumbbell One-Arm Upright Row": "Dumbbell_One-Arm_Upright_Row",
  "Dumbbell Prone Incline Curl": "Dumbbell_Prone_Incline_Curl",
  "Dumbbell Raise": "Dumbbell_Raise",
  "Dumbbell Rear Lunge": "Dumbbell_Rear_Lunge",
  "Dumbbell Scaption": "Dumbbell_Scaption",
  "Dumbbell Seated Box Jump": "Dumbbell_Seated_Box_Jump",
  "Dumbbell Seated One-Leg Calf Raise": "Dumbbell_Seated_One-Leg_Calf_Raise",
  "Dumbbell Side Bend": "Dumbbell_Side_Bend",
  "Dumbbell Squat To A Bench": "Dumbbell_Squat_To_A_Bench",
  "Dumbbell Step Ups": "Dumbbell_Step_Ups",
  "Dumbbell Tricep Extension -Pronated Grip": "Dumbbell_Tricep_Extension_-Pronated_Grip",
  "Dynamic Back Stretch": "Dynamic_Back_Stretch",
  "Dynamic Chest Stretch": "Dynamic_Chest_Stretch",
  "EZ-Bar Skullcrusher": "EZ-Bar_Skullcrusher",
  "Elbow Circles": "Elbow_Circles",
  "Elbow to Knee": "Elbow_to_Knee",
  "Elbows Back": "Elbows_Back",
  "Elevated Back Lunge": "Elevated_Back_Lunge",
  "Elevated Cable Rows": "Elevated_Cable_Rows",
  "Elliptical Trainer": "Elliptical_Trainer",
  "Exercise Ball Crunch": "Exercise_Ball_Crunch",
  "Exercise Ball Pull-In": "Exercise_Ball_Pull-In",
  "Extended Range One-Arm Kettlebell Floor Press": "Extended_Range_One-Arm_Kettlebell_Floor_Press",
  "External Rotation": "External_Rotation",
  "External Rotation with Band": "External_Rotation_with_Band",
  "External Rotation with Cable": "External_Rotation_with_Cable",
  "Fast Skipping": "Fast_Skipping",
  "Finger Curls": "Finger_Curls",
  "Flat Bench Cable Flyes": "Flat_Bench_Cable_Flyes",
  "Flat Bench Leg Pull-In": "Flat_Bench_Leg_Pull-In",
  "Flat Bench Lying Leg Raise": "Flat_Bench_Lying_Leg_Raise",
  "Flexor Incline Dumbbell Curls": "Flexor_Incline_Dumbbell_Curls",
  "Floor Glute-Ham Raise": "Floor_Glute-Ham_Raise",
  "Floor Press": "Floor_Press",
  "Floor Press with Chains": "Floor_Press_with_Chains",
  "Foot-SMR": "Foot-SMR",
  "Forward Drag with Press": "Forward_Drag_with_Press",
  "Frankenstein Squat": "Frankenstein_Squat",
  "Freehand Jump Squat": "Freehand_Jump_Squat",
  "Frog Hops": "Frog_Hops",
  "Frog Sit-Ups": "Frog_Sit-Ups",
  "Front Barbell Squat": "Front_Barbell_Squat",
  "Front Barbell Squat To A Bench": "Front_Barbell_Squat_To_A_Bench",
  "Front Box Jump": "Front_Box_Jump",
  "Front Cable Raise": "Front_Cable_Raise",
  "Front Cone Hops (or hurdle hops)": "Front_Cone_Hops_or_hurdle_hops",
  "Front Dumbbell Raise": "Front_Dumbbell_Raise",
  "Front Incline Dumbbell Raise": "Front_Incline_Dumbbell_Raise",
  "Front Leg Raises": "Front_Leg_Raises",
  "Front Plate Raise": "Front_Plate_Raise",
  "Front Raise And Pullover": "Front_Raise_And_Pullover",
  "Front Squat (Clean Grip)": "Front_Squat_Clean_Grip",
  "Front Squats With Two Kettlebells": "Front_Squats_With_Two_Kettlebells",
  "Front Two-Dumbbell Raise": "Front_Two-Dumbbell_Raise",
  "Full Range-Of-Motion Lat Pulldown": "Full_Range-Of-Motion_Lat_Pulldown",
  "Gironda Sternum Chins": "Gironda_Sternum_Chins",
  "Glute Kickback": "Glute_Kickback",
  "Good Morning off Pins": "Good_Morning_off_Pins",
  "Gorilla Chin/Crunch": "Gorilla_Chin_Crunch",
  "Groin and Back Stretch": "Groin_and_Back_Stretch",
  "Groiners": "Groiners",
  "Hammer Grip Incline DB Bench Press": "Hammer_Grip_Incline_DB_Bench_Press",
  "Hamstring-SMR": "Hamstring-SMR",
  "Hamstring Stretch": "Hamstring_Stretch",
  "Handstand Push-Ups": "Handstand_Push-Ups",
  "Hang Clean": "Hang_Clean",
  "Hang Clean - Below the Knees": "Hang_Clean_-_Below_the_Knees",
  "Hang Snatch": "Hang_Snatch",
  "Hang Snatch - Below Knees": "Hang_Snatch_-_Below_Knees",
  "Hanging Bar Good Morning": "Hanging_Bar_Good_Morning",
  "Hanging Pike": "Hanging_Pike",
  "Heaving Snatch Balance": "Heaving_Snatch_Balance",
  "Heavy Bag Thrust": "Heavy_Bag_Thrust",
  "High Cable Curls": "High_Cable_Curls",
  "Hip Circles (prone)": "Hip_Circles_prone",
  "Hip Extension with Bands": "Hip_Extension_with_Bands",
  "Hip Flexion with Band": "Hip_Flexion_with_Band",
  "Hip Lift with Band": "Hip_Lift_with_Band",
  "Hug A Ball": "Hug_A_Ball",
  "Hug Knees To Chest": "Hug_Knees_To_Chest",
  "Hurdle Hops": "Hurdle_Hops",
  "Hyperextensions (Back Extensions)": "Hyperextensions_Back_Extensions",
  "Hyperextensions With No Hyperextension Bench": "Hyperextensions_With_No_Hyperextension_Bench",
  "IT Band and Glute Stretch": "IT_Band_and_Glute_Stretch",
  "Iliotibial Tract-SMR": "Iliotibial_Tract-SMR",
  "Inchworm": "Inchworm",
  "Incline Barbell Triceps Extension": "Incline_Barbell_Triceps_Extension",
  "Incline Bench Pull": "Incline_Bench_Pull",
  "Incline Cable Chest Press": "Incline_Cable_Chest_Press",
  "Incline Cable Flye": "Incline_Cable_Flye",
  "Incline Dumbbell Bench With Palms Facing In": "Incline_Dumbbell_Bench_With_Palms_Facing_In",
  "Incline Dumbbell Flyes": "Incline_Dumbbell_Flyes",
  "Incline Dumbbell Flyes - With A Twist": "Incline_Dumbbell_Flyes_-_With_A_Twist",
  "Incline Hammer Curls": "Incline_Hammer_Curls",
  "Incline Inner Biceps Curl": "Incline_Inner_Biceps_Curl",
  "Incline Push-Up": "Incline_Push-Up",
  "Incline Push-Up Close-Grip": "Incline_Push-Up_Close-Grip",
  "Incline Push-Up Depth Jump": "Incline_Push-Up_Depth_Jump",
  "Incline Push-Up Medium": "Incline_Push-Up_Medium",
  "Incline Push-Up Reverse Grip": "Incline_Push-Up_Reverse_Grip",
  "Incline Push-Up Wide": "Incline_Push-Up_Wide",
  "Intermediate Groin Stretch": "Intermediate_Groin_Stretch",
  "Intermediate Hip Flexor and Quad Stretch": "Intermediate_Hip_Flexor_and_Quad_Stretch",
  "Internal Rotation with Band": "Internal_Rotation_with_Band",
  "Inverted Row with Straps": "Inverted_Row_with_Straps",
  "Iron Cross": "Iron_Cross",
  "Iron Crosses (stretch)": "Iron_Crosses_stretch",
  "Isometric Chest Squeezes": "Isometric_Chest_Squeezes",
  "Isometric Neck Exercise - Front And Back": "Isometric_Neck_Exercise_-_Front_And_Back",
  "Isometric Neck Exercise - Sides": "Isometric_Neck_Exercise_-_Sides",
  "Isometric Wipers": "Isometric_Wipers",
  "Jackknife Sit-Up": "Jackknife_Sit-Up",
  "Janda Sit-Up": "Janda_Sit-Up",
  "Jefferson Squats": "Jefferson_Squats",
  "Jerk Balance": "Jerk_Balance",
  "Jerk Dip Squat": "Jerk_Dip_Squat",
  "Jogging, Treadmill": "Jogging_Treadmill",
  "Keg Load": "Keg_Load",
  "Kettlebell Arnold Press": "Kettlebell_Arnold_Press",
  "Kettlebell Dead Clean": "Kettlebell_Dead_Clean",
  "Kettlebell Figure 8": "Kettlebell_Figure_8",
  "Kettlebell Hang Clean": "Kettlebell_Hang_Clean",
  "Kettlebell One-Legged Deadlift": "Kettlebell_One-Legged_Deadlift",
  "Kettlebell Pass Between The Legs": "Kettlebell_Pass_Between_The_Legs",
  "Kettlebell Pirate Ships": "Kettlebell_Pirate_Ships",
  "Kettlebell Pistol Squat": "Kettlebell_Pistol_Squat",
  "Kettlebell Seated Press": "Kettlebell_Seated_Press",
  "Kettlebell Seesaw Press": "Kettlebell_Seesaw_Press",
  "Kettlebell Sumo High Pull": "Kettlebell_Sumo_High_Pull",
  "Kettlebell Turkish Get-Up (Lunge style)": "Kettlebell_Turkish_Get-Up_Lunge_style",
  "Kettlebell Turkish Get-Up (Squat style)": "Kettlebell_Turkish_Get-Up_Squat_style",
  "Kipping Muscle Up": "Kipping_Muscle_Up",
  "Knee Across The Body": "Knee_Across_The_Body",
  "Knee Circles": "Knee_Circles",
  "Knee/Hip Raise On Parallel Bars": "Knee_Hip_Raise_On_Parallel_Bars",
  "Knee Tuck Jump": "Knee_Tuck_Jump",
  "Kneeling Arm Drill": "Kneeling_Arm_Drill",
  "Kneeling Cable Crunch With Alternating Oblique Twists": "Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists",
  "Kneeling Cable Triceps Extension": "Kneeling_Cable_Triceps_Extension",
  "Kneeling Forearm Stretch": "Kneeling_Forearm_Stretch",
  "Kneeling High Pulley Row": "Kneeling_High_Pulley_Row",
  "Kneeling Hip Flexor": "Kneeling_Hip_Flexor",
  "Kneeling Jump Squat": "Kneeling_Jump_Squat",
  "Kneeling Single-Arm High Pulley Row": "Kneeling_Single-Arm_High_Pulley_Row",
  "Kneeling Squat": "Kneeling_Squat",
  "Landmine 180's": "Landmine_180s",
  "Landmine Linear Jammer": "Landmine_Linear_Jammer",
  "Lateral Bound": "Lateral_Bound",
  "Lateral Box Jump": "Lateral_Box_Jump",
  "Lateral Cone Hops": "Lateral_Cone_Hops",
  "Lateral Raise - With Bands": "Lateral_Raise_-_With_Bands",
  "Latissimus Dorsi-SMR": "Latissimus_Dorsi-SMR",
  "Leg-Over Floor Press": "Leg-Over_Floor_Press",
  "Leg-Up Hamstring Stretch": "Leg-Up_Hamstring_Stretch",
  "Leg Extensions": "Leg_Extensions",
  "Leg Lift": "Leg_Lift",
  "Leg Pull-In": "Leg_Pull-In",
  "Leverage Chest Press": "Leverage_Chest_Press",
  "Leverage Deadlift": "Leverage_Deadlift",
  "Leverage Decline Chest Press": "Leverage_Decline_Chest_Press",
  "Leverage High Row": "Leverage_High_Row",
  "Leverage Incline Chest Press": "Leverage_Incline_Chest_Press",
  "Leverage Iso Row": "Leverage_Iso_Row",
  "Leverage Shoulder Press": "Leverage_Shoulder_Press",
  "Leverage Shrug": "Leverage_Shrug",
  "Linear 3-Part Start Technique": "Linear_3-Part_Start_Technique",
  "Linear Acceleration Wall Drill": "Linear_Acceleration_Wall_Drill",
  "Linear Depth Jump": "Linear_Depth_Jump",
  "Log Lift": "Log_Lift",
  "London Bridges": "London_Bridges",
  "Looking At Ceiling": "Looking_At_Ceiling",
  "Low Cable Crossover": "Low_Cable_Crossover",
  "Low Cable Triceps Extension": "Low_Cable_Triceps_Extension",
  "Low Pulley Row To Neck": "Low_Pulley_Row_To_Neck",
  "Lower Back-SMR": "Lower_Back-SMR",
  "Lower Back Curl": "Lower_Back_Curl",
  "Lunge Pass Through": "Lunge_Pass_Through",
  "Lunge Sprint": "Lunge_Sprint",
  "Lying Bent Leg Groin": "Lying_Bent_Leg_Groin",
  "Lying Cable Curl": "Lying_Cable_Curl",
  "Lying Cambered Barbell Row": "Lying_Cambered_Barbell_Row",
  "Lying Close-Grip Bar Curl On High Pulley": "Lying_Close-Grip_Bar_Curl_On_High_Pulley",
  "Lying Close-Grip Barbell Triceps Extension Behind The Head": "Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head",
  "Lying Close-Grip Barbell Triceps Press To Chin": "Lying_Close-Grip_Barbell_Triceps_Press_To_Chin",
  "Lying Crossover": "Lying_Crossover",
  "Lying Dumbbell Tricep Extension": "Lying_Dumbbell_Tricep_Extension",
  "Lying Face Down Plate Neck Resistance": "Lying_Face_Down_Plate_Neck_Resistance",
  "Lying Face Up Plate Neck Resistance": "Lying_Face_Up_Plate_Neck_Resistance",
  "Lying Glute": "Lying_Glute",
  "Lying Hamstring": "Lying_Hamstring",
  "Lying High Bench Barbell Curl": "Lying_High_Bench_Barbell_Curl",
  "Lying Leg Curls": "Lying_Leg_Curls",
  "Lying Machine Squat": "Lying_Machine_Squat",
  "Lying One-Arm Lateral Raise": "Lying_One-Arm_Lateral_Raise",
  "Lying Prone Quadriceps": "Lying_Prone_Quadriceps",
  "Lying Rear Delt Raise": "Lying_Rear_Delt_Raise",
  "Lying Supine Dumbbell Curl": "Lying_Supine_Dumbbell_Curl",
  "Lying T-Bar Row": "Lying_T-Bar_Row",
  "Lying Triceps Press": "Lying_Triceps_Press",
  "Machine Bench Press": "Machine_Bench_Press",
  "Machine Bicep Curl": "Machine_Bicep_Curl",
  "Machine Preacher Curls": "Machine_Preacher_Curls",
  "Machine Shoulder (Military) Press": "Machine_Shoulder_Military_Press",
  "Machine Triceps Extension": "Machine_Triceps_Extension",
  "Medicine Ball Chest Pass": "Medicine_Ball_Chest_Pass",
  "Medicine Ball Full Twist": "Medicine_Ball_Full_Twist",
  "Medicine Ball Scoop Throw": "Medicine_Ball_Scoop_Throw",
  "Middle Back Shrug": "Middle_Back_Shrug",
  "Middle Back Stretch": "Middle_Back_Stretch",
  "Mixed Grip Chin": "Mixed_Grip_Chin",
  "Monster Walk": "Monster_Walk",
  "Moving Claw Series": "Moving_Claw_Series",
  "Muscle Snatch": "Muscle_Snatch",
  "Muscle Up": "Muscle_Up",
  "Narrow Stance Hack Squats": "Narrow_Stance_Hack_Squats",
  "Narrow Stance Leg Press": "Narrow_Stance_Leg_Press",
  "Narrow Stance Squats": "Narrow_Stance_Squats",
  "Natural Glute Ham Raise": "Natural_Glute_Ham_Raise",
  "Neck-SMR": "Neck-SMR",
  "Neck Press": "Neck_Press",
  "Oblique Crunches": "Oblique_Crunches",
  "Oblique Crunches - On The Floor": "Oblique_Crunches_-_On_The_Floor",
  "Olympic Squat": "Olympic_Squat",
  "On-Your-Back Quad Stretch": "On-Your-Back_Quad_Stretch",
  "On Your Side Quad Stretch": "On_Your_Side_Quad_Stretch",
  "One-Arm Flat Bench Dumbbell Flye": "One-Arm_Flat_Bench_Dumbbell_Flye",
  "One-Arm High-Pulley Cable Side Bends": "One-Arm_High-Pulley_Cable_Side_Bends",
  "One-Arm Incline Lateral Raise": "One-Arm_Incline_Lateral_Raise",
  "One-Arm Kettlebell Clean": "One-Arm_Kettlebell_Clean",
  "One-Arm Kettlebell Clean and Jerk": "One-Arm_Kettlebell_Clean_and_Jerk",
  "One-Arm Kettlebell Floor Press": "One-Arm_Kettlebell_Floor_Press",
  "One-Arm Kettlebell Jerk": "One-Arm_Kettlebell_Jerk",
  "One-Arm Kettlebell Military Press To The Side": "One-Arm_Kettlebell_Military_Press_To_The_Side",
  "One-Arm Kettlebell Para Press": "One-Arm_Kettlebell_Para_Press",
  "One-Arm Kettlebell Push Press": "One-Arm_Kettlebell_Push_Press",
  "One-Arm Kettlebell Row": "One-Arm_Kettlebell_Row",
  "One-Arm Kettlebell Snatch": "One-Arm_Kettlebell_Snatch",
  "One-Arm Kettlebell Split Jerk": "One-Arm_Kettlebell_Split_Jerk",
  "One-Arm Kettlebell Split Snatch": "One-Arm_Kettlebell_Split_Snatch",
  "One-Arm Kettlebell Swings": "One-Arm_Kettlebell_Swings",
  "One-Arm Long Bar Row": "One-Arm_Long_Bar_Row",
  "One-Arm Medicine Ball Slam": "One-Arm_Medicine_Ball_Slam",
  "One-Arm Open Palm Kettlebell Clean": "One-Arm_Open_Palm_Kettlebell_Clean",
  "One-Arm Overhead Kettlebell Squats": "One-Arm_Overhead_Kettlebell_Squats",
  "One-Arm Side Deadlift": "One-Arm_Side_Deadlift",
  "One-Arm Side Laterals": "One-Arm_Side_Laterals",
  "One-Legged Cable Kickback": "One-Legged_Cable_Kickback",
  "One Arm Against Wall": "One_Arm_Against_Wall",
  "One Arm Chin-Up": "One_Arm_Chin-Up",
  "One Arm Dumbbell Bench Press": "One_Arm_Dumbbell_Bench_Press",
  "One Arm Dumbbell Preacher Curl": "One_Arm_Dumbbell_Preacher_Curl",
  "One Arm Floor Press": "One_Arm_Floor_Press",
  "One Arm Lat Pulldown": "One_Arm_Lat_Pulldown",
  "One Arm Pronated Dumbbell Triceps Extension": "One_Arm_Pronated_Dumbbell_Triceps_Extension",
  "One Arm Supinated Dumbbell Triceps Extension": "One_Arm_Supinated_Dumbbell_Triceps_Extension",
  "One Half Locust": "One_Half_Locust",
  "One Handed Hang": "One_Handed_Hang",
  "One Knee To Chest": "One_Knee_To_Chest",
  "One Leg Barbell Squat": "One_Leg_Barbell_Squat",
  "Open Palm Kettlebell Clean": "Open_Palm_Kettlebell_Clean",
  "Otis-Up": "Otis-Up",
  "Overhead Cable Curl": "Overhead_Cable_Curl",
  "Overhead Lat": "Overhead_Lat",
  "Overhead Slam": "Overhead_Slam",
  "Overhead Squat": "Overhead_Squat",
  "Overhead Stretch": "Overhead_Stretch",
  "Overhead Triceps": "Overhead_Triceps",
  "Pallof Press With Rotation": "Pallof_Press_With_Rotation",
  "Palms-Down Dumbbell Wrist Curl Over A Bench": "Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench",
  "Palms-Down Wrist Curl Over A Bench": "Palms-Down_Wrist_Curl_Over_A_Bench",
  "Palms-Up Barbell Wrist Curl Over A Bench": "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench",
  "Palms-Up Dumbbell Wrist Curl Over A Bench": "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench",
  "Parallel Bar Dip": "Parallel_Bar_Dip",
  "Pelvic Tilt Into Bridge": "Pelvic_Tilt_Into_Bridge",
  "Peroneals-SMR": "Peroneals-SMR",
  "Peroneals Stretch": "Peroneals_Stretch",
  "Physioball Hip Bridge": "Physioball_Hip_Bridge",
  "Pin Presses": "Pin_Presses",
  "Piriformis-SMR": "Piriformis-SMR",
  "Plate Twist": "Plate_Twist",
  "Platform Hamstring Slides": "Platform_Hamstring_Slides",
  "Plie Dumbbell Squat": "Plie_Dumbbell_Squat",
  "Plyo Kettlebell Pushups": "Plyo_Kettlebell_Pushups",
  "Plyo Push-up": "Plyo_Push-up",
  "Posterior Tibialis Stretch": "Posterior_Tibialis_Stretch",
  "Power Clean from Blocks": "Power_Clean_from_Blocks",
  "Power Jerk": "Power_Jerk",
  "Power Partials": "Power_Partials",
  "Power Snatch": "Power_Snatch",
  "Power Snatch from Blocks": "Power_Snatch_from_Blocks",
  "Power Stairs": "Power_Stairs",
  "Preacher Hammer Dumbbell Curl": "Preacher_Hammer_Dumbbell_Curl",
  "Press Sit-Up": "Press_Sit-Up",
  "Prone Manual Hamstring": "Prone_Manual_Hamstring",
  "Prowler Sprint": "Prowler_Sprint",
  "Pull Through": "Pull_Through",
  "Pullups": "Pullups",
  "Push-Up Wide": "Push-Up_Wide",
  "Push-Ups - Close Triceps Position": "Push-Ups_-_Close_Triceps_Position",
  "Push-Ups With Feet Elevated": "Push-Ups_With_Feet_Elevated",
  "Push-Ups With Feet On An Exercise Ball": "Push-Ups_With_Feet_On_An_Exercise_Ball",
  "Push Press": "Push_Press",
  "Push Press - Behind the Neck": "Push_Press_-_Behind_the_Neck",
  "Push Up to Side Plank": "Push_Up_to_Side_Plank",
  "Pushups": "Pushups",
  "Pushups (Close and Wide Hand Positions)": "Pushups_Close_and_Wide_Hand_Positions",
  "Pyramid": "Pyramid",
  "Quad Stretch": "Quad_Stretch",
  "Quadriceps-SMR": "Quadriceps-SMR",
  "Quick Leap": "Quick_Leap",
  "Rack Delivery": "Rack_Delivery",
  "Rack Pull with Bands": "Rack_Pull_with_Bands",
  "Rack Pulls": "Rack_Pulls",
  "Rear Leg Raises": "Rear_Leg_Raises",
  "Recumbent Bike": "Recumbent_Bike",
  "Return Push from Stance": "Return_Push_from_Stance",
  "Reverse Band Bench Press": "Reverse_Band_Bench_Press",
  "Reverse Band Box Squat": "Reverse_Band_Box_Squat",
  "Reverse Band Deadlift": "Reverse_Band_Deadlift",
  "Reverse Band Power Squat": "Reverse_Band_Power_Squat",
  "Reverse Band Sumo Deadlift": "Reverse_Band_Sumo_Deadlift",
  "Reverse Barbell Curl": "Reverse_Barbell_Curl",
  "Reverse Barbell Preacher Curls": "Reverse_Barbell_Preacher_Curls",
  "Reverse Cable Curl": "Reverse_Cable_Curl",
  "Reverse Crunch": "Reverse_Crunch",
  "Reverse Flyes": "Reverse_Flyes",
  "Reverse Flyes With External Rotation": "Reverse_Flyes_With_External_Rotation",
  "Reverse Grip Bent-Over Rows": "Reverse_Grip_Bent-Over_Rows",
  "Reverse Grip Triceps Pushdown": "Reverse_Grip_Triceps_Pushdown",
  "Reverse Hyperextension": "Reverse_Hyperextension",
  "Reverse Machine Flyes": "Reverse_Machine_Flyes",
  "Reverse Plate Curls": "Reverse_Plate_Curls",
  "Reverse Triceps Bench Press": "Reverse_Triceps_Bench_Press",
  "Rhomboids-SMR": "Rhomboids-SMR",
  "Rickshaw Carry": "Rickshaw_Carry",
  "Rickshaw Deadlift": "Rickshaw_Deadlift",
  "Ring Dips": "Ring_Dips",
  "Rocket Jump": "Rocket_Jump",
  "Rocking Standing Calf Raise": "Rocking_Standing_Calf_Raise",
  "Rocky Pull-Ups/Pulldowns": "Rocky_Pull-Ups_Pulldowns",
  "Romanian Deadlift from Deficit": "Romanian_Deadlift_from_Deficit",
  "Rope Climb": "Rope_Climb",
  "Rope Crunch": "Rope_Crunch",
  "Rope Jumping": "Rope_Jumping",
  "Rope Straight-Arm Pulldown": "Rope_Straight-Arm_Pulldown",
  "Round The World Shoulder Stretch": "Round_The_World_Shoulder_Stretch",
  "Rowing, Stationary": "Rowing_Stationary",
  "Runner's Stretch": "Runners_Stretch",
  "Running, Treadmill": "Running_Treadmill",
  "Sandbag Load": "Sandbag_Load",
  "Scapular Pull-Up": "Scapular_Pull-Up",
  "Scissor Kick": "Scissor_Kick",
  "Scissors Jump": "Scissors_Jump",
  "Seated Band Hamstring Curl": "Seated_Band_Hamstring_Curl",
  "Seated Barbell Military Press": "Seated_Barbell_Military_Press",
  "Seated Barbell Twist": "Seated_Barbell_Twist",
  "Seated Bent-Over One-Arm Dumbbell Triceps Extension": "Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
  "Seated Bent-Over Rear Delt Raise": "Seated_Bent-Over_Rear_Delt_Raise",
  "Seated Bent-Over Two-Arm Dumbbell Triceps Extension": "Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
  "Seated Biceps": "Seated_Biceps",
  "Seated Cable Shoulder Press": "Seated_Cable_Shoulder_Press",
  "Seated Calf Stretch": "Seated_Calf_Stretch",
  "Seated Close-Grip Concentration Barbell Curl": "Seated_Close-Grip_Concentration_Barbell_Curl",
  "Seated Dumbbell Curl": "Seated_Dumbbell_Curl",
  "Seated Dumbbell Inner Biceps Curl": "Seated_Dumbbell_Inner_Biceps_Curl",
  "Seated Dumbbell Palms-Down Wrist Curl": "Seated_Dumbbell_Palms-Down_Wrist_Curl",
  "Seated Dumbbell Palms-Up Wrist Curl": "Seated_Dumbbell_Palms-Up_Wrist_Curl",
  "Seated Dumbbell Press": "Seated_Dumbbell_Press",
  "Seated Flat Bench Leg Pull-In": "Seated_Flat_Bench_Leg_Pull-In",
  "Seated Floor Hamstring Stretch": "Seated_Floor_Hamstring_Stretch",
  "Seated Front Deltoid": "Seated_Front_Deltoid",
  "Seated Glute": "Seated_Glute",
  "Seated Good Mornings": "Seated_Good_Mornings",
  "Seated Hamstring": "Seated_Hamstring",
  "Seated Hamstring and Calf Stretch": "Seated_Hamstring_and_Calf_Stretch",
  "Seated Head Harness Neck Resistance": "Seated_Head_Harness_Neck_Resistance",
  "Seated Leg Tucks": "Seated_Leg_Tucks",
  "Seated One-Arm Dumbbell Palms-Down Wrist Curl": "Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl",
  "Seated One-Arm Dumbbell Palms-Up Wrist Curl": "Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl",
  "Seated One-arm Cable Pulley Rows": "Seated_One-arm_Cable_Pulley_Rows",
  "Seated Overhead Stretch": "Seated_Overhead_Stretch",
  "Seated Palm-Up Barbell Wrist Curl": "Seated_Palm-Up_Barbell_Wrist_Curl",
  "Seated Palms-Down Barbell Wrist Curl": "Seated_Palms-Down_Barbell_Wrist_Curl",
  "Seated Side Lateral Raise": "Seated_Side_Lateral_Raise",
  "Seated Triceps Press": "Seated_Triceps_Press",
  "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl": "Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl",
  "See-Saw Press (Alternating Side Press)": "See-Saw_Press_Alternating_Side_Press",
  "Shotgun Row": "Shotgun_Row",
  "Shoulder Circles": "Shoulder_Circles",
  "Shoulder Press - With Bands": "Shoulder_Press_-_With_Bands",
  "Shoulder Raise": "Shoulder_Raise",
  "Shoulder Stretch": "Shoulder_Stretch",
  "Side-Lying Floor Stretch": "Side-Lying_Floor_Stretch",
  "Side Bridge": "Side_Bridge",
  "Side Hop-Sprint": "Side_Hop-Sprint",
  "Side Jackknife": "Side_Jackknife",
  "Side Lateral Raise": "Side_Lateral_Raise",
  "Side Laterals to Front Raise": "Side_Laterals_to_Front_Raise",
  "Side Leg Raises": "Side_Leg_Raises",
  "Side Lying Groin Stretch": "Side_Lying_Groin_Stretch",
  "Side Neck Stretch": "Side_Neck_Stretch",
  "Side Standing Long Jump": "Side_Standing_Long_Jump",
  "Side To Side Chins": "Side_To_Side_Chins",
  "Side Wrist Pull": "Side_Wrist_Pull",
  "Side to Side Box Shuffle": "Side_to_Side_Box_Shuffle",
  "Single-Arm Cable Crossover": "Single-Arm_Cable_Crossover",
  "Single-Arm Linear Jammer": "Single-Arm_Linear_Jammer",
  "Single-Arm Push-Up": "Single-Arm_Push-Up",
  "Single-Cone Sprint Drill": "Single-Cone_Sprint_Drill",
  "Single-Leg High Box Squat": "Single-Leg_High_Box_Squat",
  "Single-Leg Hop Progression": "Single-Leg_Hop_Progression",
  "Single-Leg Lateral Hop": "Single-Leg_Lateral_Hop",
  "Single-Leg Leg Extension": "Single-Leg_Leg_Extension",
  "Single-Leg Stride Jump": "Single-Leg_Stride_Jump",
  "Single Dumbbell Raise": "Single_Dumbbell_Raise",
  "Single Leg Butt Kick": "Single_Leg_Butt_Kick",
  "Single Leg Glute Bridge": "Single_Leg_Glute_Bridge",
  "Single Leg Push-off": "Single_Leg_Push-off",
  "Sit-Up": "Sit-Up",
  "Sit Squats": "Sit_Squats",
  "Skating": "Skating",
  "Sled Drag - Harness": "Sled_Drag_-_Harness",
  "Sled Overhead Backward Walk": "Sled_Overhead_Backward_Walk",
  "Sled Overhead Triceps Extension": "Sled_Overhead_Triceps_Extension",
  "Sled Reverse Flye": "Sled_Reverse_Flye",
  "Sled Row": "Sled_Row",
  "Sledgehammer Swings": "Sledgehammer_Swings",
  "Smith Incline Shoulder Raise": "Smith_Incline_Shoulder_Raise",
  "Smith Machine Behind the Back Shrug": "Smith_Machine_Behind_the_Back_Shrug",
  "Smith Machine Bench Press": "Smith_Machine_Bench_Press",
  "Smith Machine Bent Over Row": "Smith_Machine_Bent_Over_Row",
  "Smith Machine Calf Raise": "Smith_Machine_Calf_Raise",
  "Smith Machine Close-Grip Bench Press": "Smith_Machine_Close-Grip_Bench_Press",
  "Smith Machine Decline Press": "Smith_Machine_Decline_Press",
  "Smith Machine Hang Power Clean": "Smith_Machine_Hang_Power_Clean",
  "Smith Machine Hip Raise": "Smith_Machine_Hip_Raise",
  "Smith Machine Incline Bench Press": "Smith_Machine_Incline_Bench_Press",
  "Smith Machine Leg Press": "Smith_Machine_Leg_Press",
  "Smith Machine One-Arm Upright Row": "Smith_Machine_One-Arm_Upright_Row",
  "Smith Machine Overhead Shoulder Press": "Smith_Machine_Overhead_Shoulder_Press",
  "Smith Machine Pistol Squat": "Smith_Machine_Pistol_Squat",
  "Smith Machine Reverse Calf Raises": "Smith_Machine_Reverse_Calf_Raises",
  "Smith Machine Squat": "Smith_Machine_Squat",
  "Smith Machine Stiff-Legged Deadlift": "Smith_Machine_Stiff-Legged_Deadlift",
  "Smith Machine Upright Row": "Smith_Machine_Upright_Row",
  "Smith Single-Leg Split Squat": "Smith_Single-Leg_Split_Squat",
  "Snatch": "Snatch",
  "Snatch Balance": "Snatch_Balance",
  "Snatch Deadlift": "Snatch_Deadlift",
  "Snatch Pull": "Snatch_Pull",
  "Snatch Shrug": "Snatch_Shrug",
  "Snatch from Blocks": "Snatch_from_Blocks",
  "Speed Band Overhead Triceps": "Speed_Band_Overhead_Triceps",
  "Speed Box Squat": "Speed_Box_Squat",
  "Speed Squats": "Speed_Squats",
  "Spell Caster": "Spell_Caster",
  "Spider Crawl": "Spider_Crawl",
  "Spinal Stretch": "Spinal_Stretch",
  "Split Clean": "Split_Clean",
  "Split Jerk": "Split_Jerk",
  "Split Jump": "Split_Jump",
  "Split Snatch": "Split_Snatch",
  "Split Squat with Dumbbells": "Split_Squat_with_Dumbbells",
  "Split Squats": "Split_Squats",
  "Squat Jerk": "Squat_Jerk",
  "Squat with Bands": "Squat_with_Bands",
  "Squat with Chains": "Squat_with_Chains",
  "Squat with Plate Movers": "Squat_with_Plate_Movers",
  "Squats - With Bands": "Squats_-_With_Bands",
  "Stairmaster": "Stairmaster",
  "Standing Alternating Dumbbell Press": "Standing_Alternating_Dumbbell_Press",
  "Standing Barbell Calf Raise": "Standing_Barbell_Calf_Raise",
  "Standing Barbell Press Behind Neck": "Standing_Barbell_Press_Behind_Neck",
  "Standing Bent-Over One-Arm Dumbbell Triceps Extension": "Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
  "Standing Bent-Over Two-Arm Dumbbell Triceps Extension": "Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
  "Standing Biceps Cable Curl": "Standing_Biceps_Cable_Curl",
  "Standing Biceps Stretch": "Standing_Biceps_Stretch",
  "Standing Bradford Press": "Standing_Bradford_Press",
  "Standing Cable Chest Press": "Standing_Cable_Chest_Press",
  "Standing Cable Lift": "Standing_Cable_Lift",
  "Standing Cable Wood Chop": "Standing_Cable_Wood_Chop",
  "Standing Concentration Curl": "Standing_Concentration_Curl",
  "Standing Dumbbell Calf Raise": "Standing_Dumbbell_Calf_Raise",
  "Standing Dumbbell Press": "Standing_Dumbbell_Press",
  "Standing Dumbbell Reverse Curl": "Standing_Dumbbell_Reverse_Curl",
  "Standing Dumbbell Straight-Arm Front Delt Raise Above Head": "Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head",
  "Standing Dumbbell Triceps Extension": "Standing_Dumbbell_Triceps_Extension",
  "Standing Dumbbell Upright Row": "Standing_Dumbbell_Upright_Row",
  "Standing Elevated Quad Stretch": "Standing_Elevated_Quad_Stretch",
  "Standing Front Barbell Raise Over Head": "Standing_Front_Barbell_Raise_Over_Head",
  "Standing Gastrocnemius Calf Stretch": "Standing_Gastrocnemius_Calf_Stretch",
  "Standing Hamstring and Calf Stretch": "Standing_Hamstring_and_Calf_Stretch",
  "Standing Hip Circles": "Standing_Hip_Circles",
  "Standing Hip Flexors": "Standing_Hip_Flexors",
  "Standing Inner-Biceps Curl": "Standing_Inner-Biceps_Curl",
  "Standing Lateral Stretch": "Standing_Lateral_Stretch",
  "Standing Leg Curl": "Standing_Leg_Curl",
  "Standing Long Jump": "Standing_Long_Jump",
  "Standing Low-Pulley Deltoid Raise": "Standing_Low-Pulley_Deltoid_Raise",
  "Standing Low-Pulley One-Arm Triceps Extension": "Standing_Low-Pulley_One-Arm_Triceps_Extension",
  "Standing Military Press": "Standing_Military_Press",
  "Standing Olympic Plate Hand Squeeze": "Standing_Olympic_Plate_Hand_Squeeze",
  "Standing One-Arm Cable Curl": "Standing_One-Arm_Cable_Curl",
  "Standing One-Arm Dumbbell Curl Over Incline Bench": "Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench",
  "Standing One-Arm Dumbbell Triceps Extension": "Standing_One-Arm_Dumbbell_Triceps_Extension",
  "Standing Overhead Barbell Triceps Extension": "Standing_Overhead_Barbell_Triceps_Extension",
  "Standing Palm-In One-Arm Dumbbell Press": "Standing_Palm-In_One-Arm_Dumbbell_Press",
  "Standing Palms-In Dumbbell Press": "Standing_Palms-In_Dumbbell_Press",
  "Standing Palms-Up Barbell Behind The Back Wrist Curl": "Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl",
  "Standing Pelvic Tilt": "Standing_Pelvic_Tilt",
  "Standing Rope Crunch": "Standing_Rope_Crunch",
  "Standing Soleus And Achilles Stretch": "Standing_Soleus_And_Achilles_Stretch",
  "Standing Toe Touches": "Standing_Toe_Touches",
  "Standing Towel Triceps Extension": "Standing_Towel_Triceps_Extension",
  "Standing Two-Arm Overhead Throw": "Standing_Two-Arm_Overhead_Throw",
  "Star Jump": "Star_Jump",
  "Step-up with Knee Raise": "Step-up_with_Knee_Raise",
  "Step Mill": "Step_Mill",
  "Stiff-Legged Barbell Deadlift": "Stiff-Legged_Barbell_Deadlift",
  "Stiff-Legged Dumbbell Deadlift": "Stiff-Legged_Dumbbell_Deadlift",
  "Stiff Leg Barbell Good Morning": "Stiff_Leg_Barbell_Good_Morning",
  "Stomach Vacuum": "Stomach_Vacuum",
  "Straight-Arm Dumbbell Pullover": "Straight-Arm_Dumbbell_Pullover",
  "Straight-Arm Pulldown": "Straight-Arm_Pulldown",
  "Straight Bar Bench Mid Rows": "Straight_Bar_Bench_Mid_Rows",
  "Straight Raises on Incline Bench": "Straight_Raises_on_Incline_Bench",
  "Stride Jump Crossover": "Stride_Jump_Crossover",
  "Sumo Deadlift with Bands": "Sumo_Deadlift_with_Bands",
  "Sumo Deadlift with Chains": "Sumo_Deadlift_with_Chains",
  "Supine Chest Throw": "Supine_Chest_Throw",
  "Supine One-Arm Overhead Throw": "Supine_One-Arm_Overhead_Throw",
  "Supine Two-Arm Overhead Throw": "Supine_Two-Arm_Overhead_Throw",
  "Suspended Fallout": "Suspended_Fallout",
  "Suspended Push-Up": "Suspended_Push-Up",
  "Suspended Reverse Crunch": "Suspended_Reverse_Crunch",
  "Suspended Row": "Suspended_Row",
  "Suspended Split Squat": "Suspended_Split_Squat",
  "Svend Press": "Svend_Press",
  "T-Bar Row with Handle": "T-Bar_Row_with_Handle",
  "Tate Press": "Tate_Press",
  "The Straddle": "The_Straddle",
  "Thigh Abductor": "Thigh_Abductor",
  "Thigh Adductor": "Thigh_Adductor",
  "Tire Flip": "Tire_Flip",
  "Toe Touchers": "Toe_Touchers",
  "Torso Rotation": "Torso_Rotation",
  "Trail Running/Walking": "Trail_Running_Walking",
  "Tricep Dumbbell Kickback": "Tricep_Dumbbell_Kickback",
  "Tricep Side Stretch": "Tricep_Side_Stretch",
  "Triceps Overhead Extension with Rope": "Triceps_Overhead_Extension_with_Rope",
  "Triceps Pushdown": "Triceps_Pushdown",
  "Triceps Pushdown - Rope Attachment": "Triceps_Pushdown_-_Rope_Attachment",
  "Triceps Pushdown - V-Bar Attachment": "Triceps_Pushdown_-_V-Bar_Attachment",
  "Triceps Stretch": "Triceps_Stretch",
  "Tuck Crunch": "Tuck_Crunch",
  "Two-Arm Dumbbell Preacher Curl": "Two-Arm_Dumbbell_Preacher_Curl",
  "Two-Arm Kettlebell Clean": "Two-Arm_Kettlebell_Clean",
  "Two-Arm Kettlebell Jerk": "Two-Arm_Kettlebell_Jerk",
  "Two-Arm Kettlebell Military Press": "Two-Arm_Kettlebell_Military_Press",
  "Two-Arm Kettlebell Row": "Two-Arm_Kettlebell_Row",
  "Underhand Cable Pulldowns": "Underhand_Cable_Pulldowns",
  "Upper Back-Leg Grab": "Upper_Back-Leg_Grab",
  "Upper Back Stretch": "Upper_Back_Stretch",
  "Upright Barbell Row": "Upright_Barbell_Row",
  "Upright Cable Row": "Upright_Cable_Row",
  "Upright Row - With Bands": "Upright_Row_-_With_Bands",
  "Upward Stretch": "Upward_Stretch",
  "V-Bar Pulldown": "V-Bar_Pulldown",
  "V-Bar Pullup": "V-Bar_Pullup",
  "Vertical Swing": "Vertical_Swing",
  "Walking, Treadmill": "Walking_Treadmill",
  "Weighted Ball Hyperextension": "Weighted_Ball_Hyperextension",
  "Weighted Ball Side Bend": "Weighted_Ball_Side_Bend",
  "Weighted Bench Dip": "Weighted_Bench_Dip",
  "Weighted Crunches": "Weighted_Crunches",
  "Weighted Jump Squat": "Weighted_Jump_Squat",
  "Weighted Pull Ups": "Weighted_Pull_Ups",
  "Weighted Sissy Squat": "Weighted_Sissy_Squat",
  "Weighted Sit-Ups - With Bands": "Weighted_Sit-Ups_-_With_Bands",
  "Weighted Squat": "Weighted_Squat",
  "Wide-Grip Barbell Bench Press": "Wide-Grip_Barbell_Bench_Press",
  "Wide-Grip Decline Barbell Bench Press": "Wide-Grip_Decline_Barbell_Bench_Press",
  "Wide-Grip Decline Barbell Pullover": "Wide-Grip_Decline_Barbell_Pullover",
  "Wide-Grip Pulldown Behind The Neck": "Wide-Grip_Pulldown_Behind_The_Neck",
  "Wide-Grip Rear Pull-Up": "Wide-Grip_Rear_Pull-Up",
  "Wide-Grip Standing Barbell Curl": "Wide-Grip_Standing_Barbell_Curl",
  "Wide Stance Barbell Squat": "Wide_Stance_Barbell_Squat",
  "Wide Stance Stiff Legs": "Wide_Stance_Stiff_Legs",
  "Wind Sprints": "Wind_Sprints",
  "Windmills": "Windmills",
  "World's Greatest Stretch": "Worlds_Greatest_Stretch",
  "Wrist Circles": "Wrist_Circles",
  "Wrist Roller": "Wrist_Roller",
  "Wrist Rotations with Straight Bar": "Wrist_Rotations_with_Straight_Bar",
  "Yoke Walk": "Yoke_Walk",
  "Zercher Squats": "Zercher_Squats",
  "Zottman Curl": "Zottman_Curl",
  "Zottman Preacher Curl": "Zottman_Preacher_Curl",
  // ── Chest ──────────────────────────────────────────────────────────
  "Bench Press":                   "Barbell_Bench_Press_-_Medium_Grip",
  "Barbell Bench Press":           "Barbell_Bench_Press_-_Medium_Grip",
  "Incline Barbell Bench Press":   "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "Decline Barbell Bench Press":   "Barbell_Bench_Press_-_Medium_Grip",
  "Dumbbell Bench Press":          "Dumbbell_Bench_Press",
  "Incline Dumbbell Press":        "Incline_Dumbbell_Press",
  "Dumbbell Flyes":                "Dumbbell_Flyes",
  "Cable Flyes":                   "Cable_Crossover",
  "Machine Chest Press":           "Dumbbell_Bench_Press",
  "Pec Deck":                      "Dumbbell_Bench_Press",
  "Push-Ups":                      "Decline_Push-Up",
  "Chest Dips":                    "Dips_-_Chest_Version",
  "Landmine Press":                "Barbell_Shoulder_Press",
  "Diamond Push-Ups":              "Close-Grip_Push-Up_off_of_a_Dumbbell",
  "Dips":                          "Dips_-_Triceps_Version",

  // ── Back ───────────────────────────────────────────────────────────
  "Deadlift":                      "Barbell_Deadlift",
  "Barbell Row":                   "Bent_Over_Barbell_Row",
  "Barbell Rows":                  "Bent_Over_Barbell_Row",
  "Dumbbell Row":                  "Bent_Over_Two-Dumbbell_Row",
  "One-Arm Dumbbell Row":          "One-Arm_Dumbbell_Row",
  "Pendlay Row":                   "Bent_Over_Barbell_Row",
  "T-Bar Row":                     "Lying_T-Bar_Row",
  "Meadows Row":                   "Bent_Over_Barbell_Row",
  "Seated Cable Row":              "Elevated_Cable_Rows",
  "Seated Cable Rows":             "Elevated_Cable_Rows",
  "Lat Pulldown":                  "Close-Grip_Front_Lat_Pulldown",
  "Lat Pulldowns":                 "Close-Grip_Front_Lat_Pulldown",
  "Wide Grip Lat Pulldown":        "Full_Range-Of-Motion_Lat_Pulldown",
  "Wide-Grip Lat Pulldown":        "Full_Range-Of-Motion_Lat_Pulldown",
  "Pull-Ups":                      "Band_Assisted_Pull-Up",
  "Pull Ups":                      "Band_Assisted_Pull-Up",
  "Chin-Ups":                      "Band_Assisted_Pull-Up",
  "Cable Pullover":                "Barbell_Deadlift",
  "Straight Arm Pulldown":         "Barbell_Deadlift",
  "Machine Row":                   "Elevated_Cable_Rows",
  "Chest Supported Row":           "Dumbbell_Incline_Row",
  "Hyperextension":                "Hyperextensions_With_No_Hyperextension_Bench",
  "Trap Bar Deadlift":             "Barbell_Deadlift",
  "Rack Pull":                     "Barbell_Deadlift",
  "Good Morning":                  "Barbell_Deadlift",
  "Barbell Bent-Over Row":         "Bent_Over_Barbell_Row",
  "Barbell Back Squat":            "Barbell_Full_Squat",
  "Barbell Deadlift":              "Barbell_Deadlift",
  "Barbell Hip Thrust":            "Barbell_Hip_Thrust",
  "Barbell Overhead Press":        "Barbell_Shoulder_Press",
  "Deficit Deadlift":              "Barbell_Deadlift",

  // ── Shoulders ──────────────────────────────────────────────────────
  "Overhead Press":                "Barbell_Shoulder_Press",
  "Dumbbell Shoulder Press":       "Dumbbell_Shoulder_Press",
  "Arnold Press":                  "Arnold_Dumbbell_Press",
  "Arnold Dumbbell Press":         "Arnold_Dumbbell_Press",
  "Lateral Raise":                 "Cable_Seated_Lateral_Raise",
  "Lateral Raises":                "Cable_Seated_Lateral_Raise",
  "Cable Lateral Raise":           "Cable_Seated_Lateral_Raise",
  "Machine Lateral Raise":         "Cable_Seated_Lateral_Raise",
  "Front Raise":                   "Front_Dumbbell_Raise",
  "Front Raises":                  "Front_Dumbbell_Raise",
  "Rear Delt Fly":                 "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
  "Rear Delt Flyes":               "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
  "Bent-Over Rear Delt Flyes":     "Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench",
  "Face Pull":                     "Face_Pull",
  "Face Pulls":                    "Face_Pull",
  "Cable Face Pulls":              "Face_Pull",
  "Upright Row":                   "Barbell_Rear_Delt_Row",
  "Barbell Upright Row":           "Barbell_Rear_Delt_Row",
  "Behind The Neck Press":         "Barbell_Shoulder_Press",
  "Machine Shoulder Press":        "Dumbbell_Shoulder_Press",
  "Shrugs":                        "Barbell_Shrug",
  "Barbell Shrug":                 "Barbell_Shrug",
  "Barbell Shrugs":                "Barbell_Shrug",
  "Dumbbell Shrug":                "Dumbbell_Shrug",
  "Dumbbell Lateral Raises":       "Cable_Seated_Lateral_Raise",
  "Dumbbell Front Raises":         "Front_Dumbbell_Raise",

  // ── Biceps ─────────────────────────────────────────────────────────
  "Bicep Curls":                   "Barbell_Curl",
  "Barbell Curl":                  "Barbell_Curl",
  "Barbell Bicep Curl":            "Barbell_Curl",
  "Dumbbell Curl":                 "Dumbbell_Bicep_Curl",
  "Dumbbell Bicep Curl":           "Dumbbell_Bicep_Curl",
  "Hammer Curl":                   "Hammer_Curls",
  "Hammer Curls":                  "Hammer_Curls",
  "Preacher Curl":                 "Machine_Preacher_Curls",
  "Incline Dumbbell Curl":         "Incline_Dumbbell_Curl",
  "Cable Curl":                    "High_Cable_Curls",
  "Concentration Curl":            "Concentration_Curls",
  "EZ-Bar Curl":                   "EZ-Bar_Curl",
  "Spider Curl":                   "Lying_Cable_Curl",
  "Reverse Curl":                  "Barbell_Curl",
  "Bayesian Curl":                 "High_Cable_Curls",

  // ── Triceps ────────────────────────────────────────────────────────
  "Tricep Pushdown":               "Cable_Incline_Pushdown",
  "Tricep Pushdowns":              "Cable_Incline_Pushdown",
  "Cable Tricep Pushdown":         "Cable_Incline_Pushdown",
  "Rope Pushdown":                 "Cable_Incline_Pushdown",
  "Skull Crushers":                "EZ-Bar_Skullcrusher",
  "Overhead Tricep Extension":     "Dumbbell_One-Arm_Triceps_Extension",
  "Tricep Dips":                   "Dips_-_Triceps_Version",
  "Tricep Kickback":               "Dumbbell_One-Arm_Triceps_Extension",
  "Close Grip Bench Press":        "Close-Grip_Barbell_Bench_Press",
  "Close-Grip Bench Press":        "Close-Grip_Barbell_Bench_Press",
  "Cable Overhead Extension":      "Dumbbell_One-Arm_Triceps_Extension",
  "JM Press":                      "Close-Grip_Barbell_Bench_Press",

  // ── Legs ───────────────────────────────────────────────────────────
  "Squats":                        "Barbell_Full_Squat",
  "Barbell Squat":                 "Barbell_Full_Squat",
  "Front Squat":                   "Barbell_Full_Squat",
  "Goblet Squat":                  "Goblet_Squat",
  "Hack Squat":                    "Hack_Squat",
  "Leg Press":                     "Leg_Press",
  "Machine Leg Press":             "Leg_Press",
  "Leg Extension":                 "Leg_Extensions",
  "Machine Leg Extension":         "Leg_Extensions",
  "Leg Curl":                      "Lying_Leg_Curls",
  "Leg Curls":                     "Lying_Leg_Curls",
  "Seated Leg Curl":               "Lying_Leg_Curls",
  "Lying Leg Curl":                "Lying_Leg_Curls",
  "Romanian Deadlift":             "Barbell_Deadlift",
  "Stiff Leg Deadlift":            "Barbell_Deadlift",
  "Sumo Deadlift":                 "Barbell_Deadlift",
  "Bulgarian Split Squat":         "Barbell_Side_Split_Squat",
  "Walking Lunges":                "Dumbbell_Lunges",
  "Reverse Lunges":                "Dumbbell_Lunges",
  "Lunges":                        "Dumbbell_Lunges",
  "Dumbbell Lunges":               "Dumbbell_Lunges",
  "Hip Thrust":                    "Barbell_Hip_Thrust",
  "Glute Bridge":                  "Barbell_Glute_Bridge",
  "Step Ups":                      "Barbell_Step_Ups",
  "Sissy Squat":                   "Barbell_Full_Squat",
  "Standing Calf Raise":           "Donkey_Calf_Raises",
  "Standing Calf Raises":          "Donkey_Calf_Raises",
  "Calf Raises":                   "Donkey_Calf_Raises",
  "Seated Calf Raise":             "Barbell_Seated_Calf_Raise",
  "Seated Calf Raises":            "Barbell_Seated_Calf_Raise",
  "Leg Press Calf Raise":          "Calf_Press_On_The_Leg_Press_Machine",
  "Nordic Hamstring Curl":         "Lying_Leg_Curls",

  // ── Core ───────────────────────────────────────────────────────────
  "Plank":                         "Dead_Bug",
  "Side Plank":                    "Dead_Bug",
  "Russian Twist":                 "Cable_Russian_Twists",
  "Russian Twists":                "Cable_Russian_Twists",
  "Hanging Leg Raise":             "Hanging_Leg_Raise",
  "Cable Crunch":                  "Cable_Crunch",
  "Ab Wheel Rollout":              "Ab_Roller",
  "Mountain Climbers":             "Mountain_Climbers",
  "Dead Bug":                      "Dead_Bug",
  "Crunches":                      "Crunches",
  "Sit-Ups":                       "3_4_Sit-Up",
  "Decline Sit-Ups":               "3_4_Sit-Up",
  "Dragon Flag":                   "Hanging_Leg_Raise",
  "Pallof Press":                  "Cable_Crunch",
  "Woodchoppers":                  "Cable_Crunch",

  // ── Traps ──────────────────────────────────────────────────────────
  "Farmer's Walk":                 "Barbell_Shrug",

  // ── Forearms ───────────────────────────────────────────────────────
  "Wrist Curl":                    "Barbell_Curl",
  "Reverse Wrist Curl":            "Barbell_Curl",

  // ── Kettlebell exercises ────────────────────────────────────────────
  "KB Goblet Squat":               "Goblet_Squat",
  "KB Swing":                      "Barbell_Deadlift",
  "KB Romanian Deadlift":          "Barbell_Deadlift",
  "KB Lunges":                     "Dumbbell_Lunges",
  "KB Bulgarian Split Squat":      "Barbell_Side_Split_Squat",
  "KB Calf Raise":                 "Donkey_Calf_Raises",
  "KB Press":                      "Barbell_Shoulder_Press",
  "KB Push Press":                 "Barbell_Shoulder_Press",
  "KB Lateral Raise":              "Cable_Seated_Lateral_Raise",
  "KB Halo":                       "Cable_Seated_Lateral_Raise",
  "KB Floor Press":                "Dumbbell_Bench_Press",
  "KB Squeeze Press":              "Dumbbell_Bench_Press",
  "KB Row":                        "Bent_Over_Two-Dumbbell_Row",
  "KB Renegade Row":               "Bent_Over_Two-Dumbbell_Row",
  "KB High Pull":                  "Barbell_Rear_Delt_Row",
  "KB Clean":                      "Barbell_Deadlift",
  "KB Snatch":                     "Barbell_Deadlift",
  "KB Curl":                       "Dumbbell_Bicep_Curl",
  "KB Hammer Curl":                "Hammer_Curls",
  "KB Overhead Tricep Extension":  "Dumbbell_One-Arm_Triceps_Extension",
  "KB Skull Crusher":              "EZ-Bar_Skullcrusher",
  "KB Turkish Get-Up":             "Dead_Bug",
  "KB Windmill":                   "Cable_Seated_Lateral_Raise",
  "KB Russian Twist":              "Cable_Russian_Twists",
  "KB Farmer's Walk":              "Barbell_Shrug",
};

/** Returns a GitHub CDN image URL for the exercise, or null if unmapped. */
export function getExerciseImageUrl(exerciseName: string): string | null {
  const id = EXERCISE_IMAGE_IDS[exerciseName];
  if (!id) return null;
  return `${BASE_URL}/${id}/0.jpg`;
}

/**
 * Returns the start/end demonstration frames for an exercise (free-exercise-db
 * ships two images per movement: `0.jpg` = start, `1.jpg` = end position).
 * Alternating between them in the detail modal produces a lightweight,
 * CORS-free movement animation that always works — no RapidAPI dependency.
 * Returns [] when the exercise is unmapped.
 */
export function getExerciseImageFrames(exerciseName: string): string[] {
  const id = EXERCISE_IMAGE_IDS[exerciseName];
  if (!id) return [];
  return [`${BASE_URL}/${id}/0.jpg`, `${BASE_URL}/${id}/1.jpg`];
}

/**
 * Per-muscle-group visual config used for the fallback card shown when
 * no image is available (unmapped exercise or network error).
 * Covers every muscle_group value used in server/db.ts seedExercises().
 */
export const MUSCLE_GROUP_META: Record<
  string,
  { color: string; icon: string; label: string }
> = {
  Chest:       { color: "#E74C3C", icon: "activity",      label: "Chest" },
  Back:        { color: "#2980B9", icon: "anchor",         label: "Back" },
  Shoulders:   { color: "#8E44AD", icon: "wind",           label: "Shoulders" },
  "Rear Delts":{ color: "#7D3C98", icon: "rotate-ccw",     label: "Rear Delts" },
  Biceps:      { color: "#F39C12", icon: "trending-up",    label: "Biceps" },
  Triceps:     { color: "#E67E22", icon: "zap",            label: "Triceps" },
  Legs:        { color: "#27AE60", icon: "chevrons-up",    label: "Legs" },
  Quads:       { color: "#27AE60", icon: "chevrons-up",    label: "Quads" },
  Hamstrings:  { color: "#16A085", icon: "chevrons-down",  label: "Hamstrings" },
  Calves:      { color: "#1ABC9C", icon: "arrow-down",     label: "Calves" },
  Glutes:      { color: "#D35400", icon: "star",           label: "Glutes" },
  Core:        { color: "#C0392B", icon: "circle",         label: "Core" },
  Traps:       { color: "#5D6D7E", icon: "arrow-up",       label: "Traps" },
  Forearms:    { color: "#F39C12", icon: "trending-up",    label: "Forearms" },
};

/** Returns visual config for a muscle group, with a sensible default. */
export function getMuscleGroupMeta(muscleGroup: string) {
  return (
    MUSCLE_GROUP_META[muscleGroup] ?? {
      color: "#6B7280",
      icon: "activity",
      label: muscleGroup || "Exercise",
    }
  );
}
